#!/usr/bin/env bash
#
# wizard.sh - guided, GUI front-end over the migration-machine engine.
#
# It adds NO new migration logic. It collects a few answers in swiftDialog,
# generates a manifest from the shipped examples, and hands off to the existing
# `migrate` engine, which renders progress through lib/ui.sh. Run on macOS in a
# desktop session:
#
#   migrate wizard
#
# swiftDialog (https://github.com/swiftDialog/swiftDialog) draws the UI. If it
# is missing the wizard offers to install it (Homebrew cask, or the notarized
# .pkg from the project's latest release). swiftDialog is itself notarized, so
# this needs no Apple Developer account of our own.
#
# Hidden entry for tests and debugging (no GUI): build the manifest from MM_*
# environment variables and exit.
#
#   MM_PKG_MGR=brew MM_DOTFILES_REPO=git@github.com:you/dotfiles.git \
#   MM_STEPS=secrets,packages,dotfiles bash lib/wizard.sh --build-only
#
set -o pipefail

# ----------------------------------------------------------------------------
# Resolve paths (lib/ lives under the repo root, next to migrate).
# ----------------------------------------------------------------------------
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  D="$(cd -P "$(dirname "$SOURCE")" && pwd)"; SOURCE="$(readlink "$SOURCE")"
  [ "${SOURCE#/}" = "$SOURCE" ] && SOURCE="$D/$SOURCE"
done
LIB_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
MIGRATE_ROOT="$(cd -P "$LIB_DIR/.." && pwd)"
export MIGRATE_ROOT
MIGRATE="$MIGRATE_ROOT/migrate"

# shellcheck disable=SC1091
. "$LIB_DIR/core.sh"

DIALOG_BIN="${DIALOG_BIN:-/usr/local/bin/dialog}"
DIALOG_OUT="${DIALOG_OUT:-/tmp/mm-wizard-dialog.json}"
WIZARD_NAME="local-wizard"
WIZARD_FILE="$MIGRATE_ROOT/manifests/$WIZARD_NAME.json"
DIALOG_ICON="SF=desktopcomputer.and.arrow.down"

# ----------------------------------------------------------------------------
# Manifest builder.
#
# python3 first (fast, matches CI), osascript/JavaScriptCore fallback because a
# stock macOS 12.3+ has no python3 until the Command Line Tools are installed,
# and the wizard generates the manifest BEFORE bootstrap installs them.
#
# Inputs (env):
#   MM_PKG_MGR        brew | port
#   MM_DOTFILES_REPO  git URL (empty => the dotfiles step is dropped)
#   MM_STEPS          comma-separated optional step ids to include
# Args: <base-manifest> <out-file>
# ----------------------------------------------------------------------------
build_manifest() {
  local base="$1" out="$2"
  if has_cmd python3; then
    MM_PKG_MGR="${MM_PKG_MGR:-brew}" \
    MM_DOTFILES_REPO="${MM_DOTFILES_REPO:-}" \
    MM_STEPS="${MM_STEPS:-}" \
    python3 - "$base" "$out" <<'PY'
import json, os, sys
base, out = sys.argv[1], sys.argv[2]
d = json.load(open(base))
pkg = os.environ.get("MM_PKG_MGR", "brew").strip() or "brew"
repo = os.environ.get("MM_DOTFILES_REPO", "").strip()
keep = set(s for s in os.environ.get("MM_STEPS", "").split(",") if s)

cfg = d.get("config") or {}
cfg["packageManager"] = pkg
if repo:
    cfg["dotfilesRepo"] = repo
d["config"] = cfg

always = {"xcode-clt", "package-manager"}   # required infrastructure, always in
steps = []
for s in (d.get("steps") or []):
    sid = s.get("id")
    if sid in always:
        steps.append(s); continue
    if sid == "dotfiles" and not repo:
        continue                            # no repo => no dotfiles step
    if sid in keep:
        steps.append(s)
d["steps"] = steps
d["name"] = "Generated by the migration-machine wizard"
d["description"] = "Created by `migrate wizard`. Safe to edit or delete."

with open(out, "w") as f:
    json.dump(d, f, indent=2)
    f.write("\n")
PY
  elif has_cmd osascript; then
    MM_PKG_MGR="${MM_PKG_MGR:-brew}" \
    MM_DOTFILES_REPO="${MM_DOTFILES_REPO:-}" \
    MM_STEPS="${MM_STEPS:-}" \
    /usr/bin/osascript -l JavaScript -e '
      function run(argv){
        var app = Application.currentApplication(); app.includeStandardAdditions = true;
        var base = argv[0], out = argv[1];
        var env = $.NSProcessInfo.processInfo.environment;
        function getenv(k){ var v = env.objectForKey(k); return v ? ObjC.unwrap(v).replace(/^\s+|\s+$/g,"") : ""; }
        var pkg = getenv("MM_PKG_MGR") || "brew";
        var repo = getenv("MM_DOTFILES_REPO");
        var keep = {}; getenv("MM_STEPS").split(",").forEach(function(x){ if(x) keep[x] = true; });
        var d = JSON.parse(app.read(Path(base)));
        var cfg = d.config || {};
        cfg.packageManager = pkg;
        if (repo) cfg.dotfilesRepo = repo;
        d.config = cfg;
        var always = { "xcode-clt": true, "package-manager": true };
        var steps = [];
        (d.steps || []).forEach(function(s){
          var id = s.id;
          if (always[id]) { steps.push(s); return; }
          if (id === "dotfiles" && !repo) return;
          if (keep[id]) steps.push(s);
        });
        d.steps = steps;
        d.name = "Generated by the migration-machine wizard";
        d.description = "Created by `migrate wizard`. Safe to edit or delete.";
        app.write(JSON.stringify(d, null, 2) + "\n", { to: Path(out), overwriting: true });
        return "ok";
      }' "$base" "$out"
  else
    echo "No JSON engine available (need python3 or osascript)." >&2
    return 1
  fi
}

base_for_pkg() {
  if [ "${1:-brew}" = "port" ]; then
    echo "$MIGRATE_ROOT/manifests/example-macports.json"
  else
    echo "$MIGRATE_ROOT/manifests/example-homebrew.json"
  fi
}

# ----------------------------------------------------------------------------
# Hidden non-GUI entry: build the manifest from MM_* env and exit.
# ----------------------------------------------------------------------------
if [ "${1:-}" = "--build-only" ]; then
  build_manifest "$(base_for_pkg "${MM_PKG_MGR:-brew}")" "$WIZARD_FILE" \
    && echo "Built $WIZARD_FILE"
  exit $?
fi

# ----------------------------------------------------------------------------
# swiftDialog plumbing.
# ----------------------------------------------------------------------------
have_dialog() { [ -x "$DIALOG_BIN" ]; }

ensure_dialog() {
  have_dialog && return 0
  echo "The guided setup needs swiftDialog, which is not installed yet."
  if has_cmd brew; then
    echo "Installing swiftDialog with Homebrew..."
    brew install --cask swiftdialog >/dev/null 2>&1
    have_dialog && return 0
  fi
  if has_cmd curl; then
    echo "Downloading swiftDialog (notarized) from its latest release..."
    local url tmp="/tmp/swiftDialog.pkg"
    url=$( curl -fsSL https://api.github.com/repos/swiftDialog/swiftDialog/releases/latest \
           | grep -o 'https://[^"]*\.pkg' | head -1 )
    if [ -n "$url" ] && curl -fsSL -o "$tmp" "$url"; then
      echo "Installing swiftDialog (you may be asked for your password)..."
      sudo /usr/sbin/installer -pkg "$tmp" -target / >/dev/null 2>&1
      have_dialog && return 0
    fi
  fi
  cat <<'EOF'

Could not install swiftDialog automatically. Install it, then re-run:
  migrate wizard

  Homebrew:  brew install --cask swiftdialog
  Manual:    https://github.com/swiftDialog/swiftDialog/releases
EOF
  return 1
}

# Run a dialog, capturing its --json result to $DIALOG_OUT. Returns the dialog
# exit code: 0 = button1, 2 = button2, 3 = info button, others = quit/cancel.
dialog_ask() {
  "$DIALOG_BIN" "$@" --json >"$DIALOG_OUT" 2>/dev/null
}

# Read one value out of the last dialog's JSON by its field label.
json_get() {
  local key="$1"
  if has_cmd python3; then
    python3 -c 'import json,sys
try:
    d = json.load(open(sys.argv[1])) or {}
except Exception:
    d = {}
print(d.get(sys.argv[2], ""))' "$DIALOG_OUT" "$key"
  else
    /usr/bin/osascript -l JavaScript -e '
      function run(a){
        var app = Application.currentApplication(); app.includeStandardAdditions = true;
        var d; try { d = JSON.parse(app.read(Path(a[0]))); } catch(e) { d = {}; }
        var v = d[a[1]]; return (v == null) ? "" : String(v);
      }' "$DIALOG_OUT" "$key"
  fi
}

# Truthy test that tolerates "true"/"True"/1 from either JSON engine.
is_true() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes) return 0 ;;
    *) return 1 ;;
  esac
}

# Expand a leading ~ or ~/ (not ~user) and trim surrounding whitespace.
clean_path() {
  local p="$1" tilde='~'
  p="${p#"${p%%[![:space:]]*}"}"        # ltrim
  p="${p%"${p##*[![:space:]]}"}"        # rtrim
  if [ "$p" = "$tilde" ]; then
    p="$HOME"
  elif [ "${p#"$tilde"/}" != "$p" ]; then
    p="$HOME/${p#"$tilde"/}"
  fi
  printf '%s' "$p"
}

# ----------------------------------------------------------------------------
# Screens
# ----------------------------------------------------------------------------
screen_welcome() {
  "$DIALOG_BIN" \
    --title "migration-machine" \
    --message "Move your whole Mac setup without Migration Assistant.\n\nIs this the Mac you are **leaving**, or the **new** one you are setting up?" \
    --icon "$DIALOG_ICON" \
    --button1text "Set up this new Mac" \
    --button2text "Back up my old Mac" \
    --moveable --ontop --width 640 --height 300 >/dev/null 2>&1
}

screen_datadir() {
  dialog_ask \
    --title "migration-machine" \
    --message "Where is your migration data folder? This is the single folder you carry between the two Macs (a cloud-synced folder, a USB drive, anything)." \
    --icon "SF=externaldrive.connected.to.line.below" \
    --textfield "Data folder,value=$HOME/migration-data" \
    --button1text "Continue" --button2text "Cancel" \
    --moveable --ontop --width 640
}

screen_provision_opts() {
  dialog_ask \
    --title "migration-machine - set up this Mac" \
    --message "Pick your package manager, point at your dotfiles if you have them, and choose what to restore. You will preview the plan before anything runs." \
    --icon "SF=gearshape.2" \
    --selecttitle "Package manager" --selectvalues "Homebrew,MacPorts" --selectdefault "Homebrew" \
    --textfield "Dotfiles repo (optional),prompt=git@github.com:you/dotfiles.git" \
    --checkbox "SSH and GPG keys" \
    --checkbox "Packages and apps" \
    --checkbox "Dotfiles" \
    --checkbox "macOS system settings" \
    --checkbox "App preferences and config" \
    --checkbox "TouchID for sudo" \
    --button1text "Preview the plan" --button2text "Cancel" \
    --moveable --ontop --width 760
}

screen_confirm_apply() {
  "$DIALOG_BIN" \
    --title "Ready to set up your Mac" \
    --message "That was a dry run. Nothing has changed yet.\n\nRun it for real now? You may be asked for your password and for the secrets passphrase." \
    --icon "SF=play.circle" \
    --button1text "Set up my Mac" --button2text "Not yet" \
    --moveable --ontop --width 640 >/dev/null 2>&1
}

screen_confirm_capture() {
  "$DIALOG_BIN" \
    --title "Back up this Mac" \
    --message "This will capture your config (dotfiles, packages, macOS settings, app preferences) and your SSH/GPG keys into an encrypted bundle, all under:\n\n**$1**\n\nYou will be asked to set a passphrase for the encrypted keys." \
    --icon "SF=arrow.down.doc" \
    --button1text "Back up now" --button2text "Cancel" \
    --moveable --ontop --width 660 >/dev/null 2>&1
}

# ----------------------------------------------------------------------------
# Flow
# ----------------------------------------------------------------------------
ensure_dialog || exit 1

screen_welcome
case $? in
  0) ROLE="provision" ;;
  2) ROLE="capture" ;;
  *) echo "Cancelled."; exit 0 ;;
esac

# Data folder (shared by both roles).
if ! screen_datadir; then echo "Cancelled."; exit 0; fi
DATA_DIR="$(clean_path "$(json_get "Data folder")")"
[ -n "$DATA_DIR" ] || DATA_DIR="$HOME/migration-data"

export MIGRATE_UI=gui

if [ "$ROLE" = "capture" ]; then
  if ! screen_confirm_capture "$DATA_DIR"; then echo "Cancelled."; exit 0; fi
  exec "$MIGRATE" --data "$DATA_DIR" capture
fi

# --- provision ---
if ! screen_provision_opts; then echo "Cancelled."; exit 0; fi

case "$(json_get "Package manager")" in
  MacPorts|port) MM_PKG_MGR="port" ;;
  *)             MM_PKG_MGR="brew" ;;
esac
MM_DOTFILES_REPO="$(json_get "Dotfiles repo (optional)")"

MM_STEPS=""
add_step() { MM_STEPS="${MM_STEPS:+$MM_STEPS,}$1"; }
is_true "$(json_get "SSH and GPG keys")"          && add_step "secrets"
is_true "$(json_get "Packages and apps")"         && add_step "packages"
is_true "$(json_get "Dotfiles")"                  && add_step "dotfiles"
is_true "$(json_get "macOS system settings")"     && add_step "macos-defaults"
is_true "$(json_get "App preferences and config")" && add_step "restore-config"
is_true "$(json_get "TouchID for sudo")"          && add_step "touchid-sudo"
export MM_PKG_MGR MM_DOTFILES_REPO MM_STEPS

if ! build_manifest "$(base_for_pkg "$MM_PKG_MGR")" "$WIZARD_FILE"; then
  echo "Could not generate the manifest." >&2
  exit 1
fi

# Preview (dry run) through the engine, then confirm the real run.
"$MIGRATE" --data "$DATA_DIR" provision -m "$WIZARD_NAME" --dry-run

if ! screen_confirm_apply; then
  echo "Stopped. Your data folder and the generated manifest are saved."
  exit 0
fi

exec "$MIGRATE" --data "$DATA_DIR" bootstrap -m "$WIZARD_NAME"
