#!/usr/bin/env bash
#
# wizard.sh - guided, GUI front-end over the migration-machine engine.
#
# It adds NO new migration logic. It collects a few answers in swiftDialog,
# generates a manifest from the shipped examples, and hands off to the existing
# `migrate` engine, which renders progress through lib/ui.sh. Run on macOS in a
# desktop session:
#
#   migrate wizard
#
# swiftDialog (https://github.com/swiftDialog/swiftDialog) draws the UI. If it
# is missing the wizard offers to install it (Homebrew cask, or the notarized
# .pkg from the project's latest release). swiftDialog is itself notarized, so
# this needs no Apple Developer account of our own.
#
# Hidden entry for tests and debugging (no GUI): build the manifest from MM_*
# environment variables and exit.
#
#   MM_PKG_MGR=brew MM_DOTFILES_REPO=git@github.com:you/dotfiles.git \
#   MM_STEPS=secrets,packages,dotfiles bash lib/wizard.sh --build-only
#
set -o pipefail

# ----------------------------------------------------------------------------
# Resolve paths (lib/ lives under the repo root, next to migrate).
# ----------------------------------------------------------------------------
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  D="$(cd -P "$(dirname "$SOURCE")" && pwd)"; SOURCE="$(readlink "$SOURCE")"
  [ "${SOURCE#/}" = "$SOURCE" ] && SOURCE="$D/$SOURCE"
done
LIB_DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
MIGRATE_ROOT="$(cd -P "$LIB_DIR/.." && pwd)"
export MIGRATE_ROOT
MIGRATE="$MIGRATE_ROOT/migrate"

# shellcheck disable=SC1091
. "$LIB_DIR/core.sh"

DIALOG_ICON="SF=desktopcomputer.and.arrow.down"

# swiftDialog's binary lands at /usr/local/bin/dialog on every Mac (its notarized
# pkg hardcodes that path). Probe the Apple-silicon Homebrew prefix too in case a
# future install relocates it, and honor an explicit DIALOG_BIN if one is set.
resolve_dialog() {
  local c
  for c in "${DIALOG_BIN:-}" /usr/local/bin/dialog /opt/homebrew/bin/dialog; do
    if [ -n "$c" ] && [ -x "$c" ]; then DIALOG_BIN="$c"; export DIALOG_BIN; return 0; fi
  done
  return 1
}

# ----------------------------------------------------------------------------
# Manifest builder.
#
# python3 first (fast, matches CI), osascript/JavaScriptCore fallback because a
# stock macOS 12.3+ has no python3 until the Command Line Tools are installed,
# and the wizard generates the manifest BEFORE bootstrap installs them.
#
# Inputs (env):
#   MM_PKG_MGR        brew | port
#   MM_DOTFILES_REPO  git URL (empty => the dotfiles step is dropped)
#   MM_STEPS          comma-separated optional step ids to include
# Args: <base-manifest> <out-file>
# ----------------------------------------------------------------------------
build_manifest() {
  local base="$1" out="$2"
  if has_cmd python3; then
    MM_PKG_MGR="${MM_PKG_MGR:-brew}" \
    MM_DOTFILES_REPO="${MM_DOTFILES_REPO:-}" \
    MM_STEPS="${MM_STEPS:-}" \
    python3 - "$base" "$out" <<'PY'
import json, os, sys
base, out = sys.argv[1], sys.argv[2]
d = json.load(open(base))
pkg = os.environ.get("MM_PKG_MGR", "brew").strip() or "brew"
repo = os.environ.get("MM_DOTFILES_REPO", "").strip()
keep = set(s.strip() for s in os.environ.get("MM_STEPS", "").split(",") if s.strip())

cfg = d.get("config") or {}
cfg["packageManager"] = pkg
if repo:
    cfg["dotfilesRepo"] = repo
else:
    cfg.pop("dotfilesRepo", None)   # no repo => don't carry the example placeholder
d["config"] = cfg

always = {"xcode-clt", "package-manager"}   # required infrastructure, always in
steps = []
for s in (d.get("steps") or []):
    sid = s.get("id")
    if sid in always:
        steps.append(s); continue
    if sid == "dotfiles" and not repo:
        continue                            # no repo => no dotfiles step
    if sid in keep:
        steps.append(s)
d["steps"] = steps
d["name"] = "Generated by the migration-machine wizard"
d["description"] = "Created by `migrate wizard`. Safe to edit or delete."

with open(out, "w") as f:
    json.dump(d, f, indent=2)
    f.write("\n")
PY
  elif has_cmd osascript; then
    # Pass inputs as argv, not env: JXA can only reach process env through the
    # ObjC bridge (needs Foundation imported and is fragile). app.read/app.write/
    # Path/JSON are the same APIs core.sh already relies on, no import needed.
    /usr/bin/osascript -l JavaScript -e '
      function run(argv){
        var app = Application.currentApplication(); app.includeStandardAdditions = true;
        var base = argv[0], out = argv[1];
        var pkg = (argv[2] || "brew");
        var repo = (argv[3] || "").replace(/^\s+|\s+$/g, "");
        var keep = {}; (argv[4] || "").split(",").forEach(function(x){ x = x.replace(/^\s+|\s+$/g, ""); if(x) keep[x] = true; });
        var d = JSON.parse(app.read(Path(base)));
        var cfg = d.config || {};
        cfg.packageManager = pkg;
        if (repo) { cfg.dotfilesRepo = repo; } else { delete cfg.dotfilesRepo; }
        d.config = cfg;
        var always = { "xcode-clt": true, "package-manager": true };
        var steps = [];
        (d.steps || []).forEach(function(s){
          var id = s.id;
          if (always[id]) { steps.push(s); return; }
          if (id === "dotfiles" && !repo) return;
          if (keep[id]) steps.push(s);
        });
        d.steps = steps;
        d.name = "Generated by the migration-machine wizard";
        d.description = "Created by `migrate wizard`. Safe to edit or delete.";
        app.write(JSON.stringify(d, null, 2) + "\n", { to: Path(out), overwriting: true });
        return "ok";
      }' "$base" "$out" "${MM_PKG_MGR:-brew}" "${MM_DOTFILES_REPO:-}" "${MM_STEPS:-}"
  else
    echo "No JSON engine available (need python3 or osascript)." >&2
    return 1
  fi
}

base_for_pkg() {
  if [ "${1:-brew}" = "port" ]; then
    echo "$MIGRATE_ROOT/manifests/example-macports.json"
  else
    echo "$MIGRATE_ROOT/manifests/example-homebrew.json"
  fi
}

# ----------------------------------------------------------------------------
# Hidden non-GUI entry: build the manifest from MM_* env and exit.
# ----------------------------------------------------------------------------
if [ "${1:-}" = "--build-only" ]; then
  data="${MIGRATION_DATA:-$HOME/migration-data}"
  mkdir -p "$data" || exit 1
  out="$data/local-wizard.json"
  build_manifest "$(base_for_pkg "${MM_PKG_MGR:-brew}")" "$out" && echo "Built $out"
  exit $?
fi

# ----------------------------------------------------------------------------
# swiftDialog plumbing.
# ----------------------------------------------------------------------------
# Per-run temp file for the dialog's JSON output, created under a private umask
# so it is not world-readable and cannot be pre-created by another user.
if [ -z "${DIALOG_OUT:-}" ]; then
  _old_umask="$(umask)"; umask 077
  DIALOG_OUT="$(mktemp "${TMPDIR:-/tmp}/mm-wizard-dialog.XXXXXX")" \
    || { umask "$_old_umask"; echo "Could not create a temp file for the dialog." >&2; exit 1; }
  umask "$_old_umask"
  trap 'rm -f "$DIALOG_OUT"' EXIT
fi

have_dialog() { resolve_dialog; }

ensure_dialog() {
  have_dialog && return 0
  echo "The guided setup needs swiftDialog, which is not installed yet."
  if has_cmd brew; then
    echo "Installing swiftDialog with Homebrew..."
    brew install --cask swiftdialog >/dev/null 2>&1
    have_dialog && return 0
  fi
  if has_cmd curl; then
    echo "Downloading swiftDialog (notarized) from its latest release..."
    local url tmpd
    # Restrict to the swiftDialog releases host, not any .pkg URL in the payload.
    url=$( curl -fsSL https://api.github.com/repos/swiftDialog/swiftDialog/releases/latest \
           | grep -o 'https://github.com/swiftDialog/swiftDialog/releases/download/[^"]*\.pkg' \
           | head -1 )
    tmpd="$(mktemp -d "${TMPDIR:-/tmp}/swiftDialog.XXXXXX")" || return 1
    if [ -n "$url" ] && curl -fsSL -o "$tmpd/swiftDialog.pkg" "$url"; then
      echo "Installing swiftDialog (you may be asked for your password)..."
      # The pkg is Apple-notarized, so installer verifies it before running.
      sudo /usr/sbin/installer -pkg "$tmpd/swiftDialog.pkg" -target / >/dev/null 2>&1
    fi
    rm -rf "$tmpd"
    have_dialog && return 0
  fi
  cat <<'EOF'

Could not install swiftDialog automatically. Install it, then re-run:
  migrate wizard

  Homebrew:  brew install --cask swiftdialog
  Manual:    https://github.com/swiftDialog/swiftDialog/releases
EOF
  return 1
}

# Run a dialog, capturing its --json result to $DIALOG_OUT. Returns the dialog
# exit code: 0 = button1, 2 = button2, 3 = info button, others = quit/cancel.
dialog_ask() {
  "$DIALOG_BIN" "$@" --json >"$DIALOG_OUT" 2>/dev/null
}

# Read one value out of the last dialog's JSON by its field label.
json_get() {
  local key="$1"
  if has_cmd python3; then
    python3 -c 'import json,sys
try:
    d = json.load(open(sys.argv[1])) or {}
except Exception:
    d = {}
print(d.get(sys.argv[2], ""))' "$DIALOG_OUT" "$key"
  else
    /usr/bin/osascript -l JavaScript -e '
      function run(a){
        var app = Application.currentApplication(); app.includeStandardAdditions = true;
        var d; try { d = JSON.parse(app.read(Path(a[0]))); } catch(e) { d = {}; }
        var v = d[a[1]]; return (v == null) ? "" : String(v);
      }' "$DIALOG_OUT" "$key"
  fi
}

# Truthy test that tolerates "true"/"True"/1 from either JSON engine.
is_true() {
  case "$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes) return 0 ;;
    *) return 1 ;;
  esac
}

# Trim leading/trailing whitespace.
trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  s="${s%"${s##*[![:space:]]}"}"
  printf '%s' "$s"
}

# Expand a leading ~ or ~/ (not ~user) and trim surrounding whitespace.
clean_path() {
  local p="$1" tilde='~'
  p="${p#"${p%%[![:space:]]*}"}"        # ltrim
  p="${p%"${p##*[![:space:]]}"}"        # rtrim
  if [ "$p" = "$tilde" ]; then
    p="$HOME"
  elif [ "${p#"$tilde"/}" != "$p" ]; then
    p="$HOME/${p#"$tilde"/}"
  fi
  printf '%s' "$p"
}

# ----------------------------------------------------------------------------
# Screens
# ----------------------------------------------------------------------------
screen_welcome() {
  "$DIALOG_BIN" \
    --title "migration-machine" \
    --message "Move your whole Mac setup without Migration Assistant.\n\nIs this the Mac you are **leaving**, or the **new** one you are setting up?" \
    --icon "$DIALOG_ICON" \
    --button1text "Set up this new Mac" \
    --button2text "Back up my old Mac" \
    --moveable --ontop --width 640 --height 300 >/dev/null 2>&1
}

screen_datadir() {
  dialog_ask \
    --title "migration-machine" \
    --message "Where is your migration data folder? This is the single folder you carry between the two Macs (a cloud-synced folder, a USB drive, anything)." \
    --icon "SF=externaldrive.connected.to.line.below" \
    --textfield "Data folder,value=$HOME/migration-data" \
    --button1text "Continue" --button2text "Cancel" \
    --moveable --ontop --width 640
}

screen_provision_opts() {
  dialog_ask \
    --title "migration-machine - set up this Mac" \
    --message "Pick your package manager, point at your dotfiles if you have them, and choose what to restore. You will preview the plan before anything runs." \
    --icon "SF=gearshape.2" \
    --selecttitle "Package manager" --selectvalues "Homebrew,MacPorts" --selectdefault "Homebrew" \
    --textfield "Dotfiles repo (optional),prompt=git@github.com:you/dotfiles.git" \
    --checkbox "SSH and GPG keys" \
    --checkbox "Packages and apps" \
    --checkbox "Dotfiles" \
    --checkbox "macOS system settings" \
    --checkbox "App preferences and config" \
    --checkbox "TouchID for sudo" \
    --button1text "Preview the plan" --button2text "Cancel" \
    --moveable --ontop --width 760
}

screen_confirm_apply() {
  "$DIALOG_BIN" \
    --title "Ready to set up your Mac" \
    --message "That was a dry run. Nothing has changed yet.\n\nRun it for real now? You may be asked for your password and for the secrets passphrase." \
    --icon "SF=play.circle" \
    --button1text "Set up my Mac" --button2text "Not yet" \
    --moveable --ontop --width 640 >/dev/null 2>&1
}

screen_confirm_capture() {
  "$DIALOG_BIN" \
    --title "Back up this Mac" \
    --message "This will capture your config (dotfiles, packages, macOS settings, app preferences) and your SSH/GPG keys into an encrypted bundle, all under:\n\n**$1**\n\nYou will be asked to set a passphrase for the encrypted keys." \
    --icon "SF=arrow.down.doc" \
    --button1text "Back up now" --button2text "Cancel" \
    --moveable --ontop --width 660 >/dev/null 2>&1
}

# ----------------------------------------------------------------------------
# Flow
# ----------------------------------------------------------------------------
# This is a desktop GUI flow. If there is no console session (e.g. over SSH),
# fail fast with a clear message instead of letting swiftDialog error opaquely.
if [ -n "${SSH_TTY:-}" ] || ! gui_session; then
  echo "The guided setup needs a desktop session on the Mac itself, not SSH." >&2
  echo "From a terminal you can still run: migrate capture  or  migrate provision -m <manifest>" >&2
  exit 1
fi

ensure_dialog || exit 1

screen_welcome
case $? in
  0) ROLE="provision" ;;
  2) ROLE="capture" ;;
  *) echo "Cancelled."; exit 0 ;;
esac

# Data folder (shared by both roles).
if ! screen_datadir; then echo "Cancelled."; exit 0; fi
DATA_DIR="$(clean_path "$(json_get "Data folder")")"
[ -n "$DATA_DIR" ] || DATA_DIR="$HOME/migration-data"

export MIGRATE_UI=gui

if [ "$ROLE" = "capture" ]; then
  if ! screen_confirm_capture "$DATA_DIR"; then echo "Cancelled."; exit 0; fi
  rm -f "$DIALOG_OUT"
  exec "$MIGRATE" --data "$DATA_DIR" capture
fi

# --- provision ---
add_step() { MM_STEPS="${MM_STEPS:+$MM_STEPS,}$1"; }
while :; do
  if ! screen_provision_opts; then echo "Cancelled."; exit 0; fi

  case "$(json_get "Package manager")" in
    MacPorts|port) MM_PKG_MGR="port" ;;
    *)             MM_PKG_MGR="brew" ;;
  esac
  MM_DOTFILES_REPO="$(trim "$(json_get "Dotfiles repo (optional)")")"

  MM_STEPS=""
  dotfiles_picked=0
  is_true "$(json_get "SSH and GPG keys")"           && add_step "secrets"
  is_true "$(json_get "Packages and apps")"          && add_step "packages"
  is_true "$(json_get "Dotfiles")"                   && { add_step "dotfiles"; dotfiles_picked=1; }
  is_true "$(json_get "macOS system settings")"      && add_step "macos-defaults"
  is_true "$(json_get "App preferences and config")" && add_step "restore-config"
  is_true "$(json_get "TouchID for sudo")"           && add_step "touchid-sudo"

  # Dotfiles selected but no repo => the step would be silently dropped. Tell the
  # user and re-prompt so the plan matches what they actually ticked.
  if [ "$dotfiles_picked" = "1" ] && [ -z "$MM_DOTFILES_REPO" ]; then
    "$DIALOG_BIN" --title "Dotfiles repo needed" \
      --message "You chose to restore Dotfiles but left the repo blank. Add your dotfiles git URL, or uncheck Dotfiles." \
      --icon "SF=exclamationmark.triangle" --button1text "Back" \
      --moveable --ontop --width 620 >/dev/null 2>&1
    continue
  fi
  break
done
export MM_PKG_MGR MM_DOTFILES_REPO MM_STEPS

# Write the generated manifest into the user-writable data dir (the install dir
# can be read-only, e.g. a Homebrew Cellar) and pass it to the engine by path.
WIZARD_FILE="$DATA_DIR/local-wizard.json"
mkdir -p "$DATA_DIR" || { echo "Cannot write to data folder: $DATA_DIR" >&2; exit 1; }
if ! build_manifest "$(base_for_pkg "$MM_PKG_MGR")" "$WIZARD_FILE"; then
  echo "Could not generate the manifest." >&2
  exit 1
fi

# Preview (dry run) through the engine. If the preview itself fails (bad manifest,
# missing files), stop here instead of proceeding to the real run.
if ! "$MIGRATE" --data "$DATA_DIR" provision -m "$WIZARD_FILE" --dry-run; then
  echo "Dry-run preview failed. Fix the reported errors before continuing." >&2
  exit 1
fi

if ! screen_confirm_apply; then
  echo "Stopped. Your data folder and the generated manifest are saved."
  exit 0
fi

rm -f "$DIALOG_OUT"
exec "$MIGRATE" --data "$DATA_DIR" bootstrap -m "$WIZARD_FILE"
